//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelloWebClient.HelloWebServiceNamespace {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HelloWebServiceNamespace.HelloWebServiceSoap")]
    public interface HelloWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name who from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Hello", ReplyAction="*")]
        HelloWebClient.HelloWebServiceNamespace.HelloResponse Hello(HelloWebClient.HelloWebServiceNamespace.HelloRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Hello", ReplyAction="*")]
        System.Threading.Tasks.Task<HelloWebClient.HelloWebServiceNamespace.HelloResponse> HelloAsync(HelloWebClient.HelloWebServiceNamespace.HelloRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Hello", Namespace="http://tempuri.org/", Order=0)]
        public HelloWebClient.HelloWebServiceNamespace.HelloRequestBody Body;
        
        public HelloRequest() {
        }
        
        public HelloRequest(HelloWebClient.HelloWebServiceNamespace.HelloRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string who;
        
        public HelloRequestBody() {
        }
        
        public HelloRequestBody(string who) {
            this.who = who;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloResponse", Namespace="http://tempuri.org/", Order=0)]
        public HelloWebClient.HelloWebServiceNamespace.HelloResponseBody Body;
        
        public HelloResponse() {
        }
        
        public HelloResponse(HelloWebClient.HelloWebServiceNamespace.HelloResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloResult;
        
        public HelloResponseBody() {
        }
        
        public HelloResponseBody(string HelloResult) {
            this.HelloResult = HelloResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface HelloWebServiceSoapChannel : HelloWebClient.HelloWebServiceNamespace.HelloWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HelloWebServiceSoapClient : System.ServiceModel.ClientBase<HelloWebClient.HelloWebServiceNamespace.HelloWebServiceSoap>, HelloWebClient.HelloWebServiceNamespace.HelloWebServiceSoap {
        
        public HelloWebServiceSoapClient() {
        }
        
        public HelloWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HelloWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HelloWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HelloWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HelloWebClient.HelloWebServiceNamespace.HelloResponse HelloWebClient.HelloWebServiceNamespace.HelloWebServiceSoap.Hello(HelloWebClient.HelloWebServiceNamespace.HelloRequest request) {
            return base.Channel.Hello(request);
        }
        
        public string Hello(string who) {
            HelloWebClient.HelloWebServiceNamespace.HelloRequest inValue = new HelloWebClient.HelloWebServiceNamespace.HelloRequest();
            inValue.Body = new HelloWebClient.HelloWebServiceNamespace.HelloRequestBody();
            inValue.Body.who = who;
            HelloWebClient.HelloWebServiceNamespace.HelloResponse retVal = ((HelloWebClient.HelloWebServiceNamespace.HelloWebServiceSoap)(this)).Hello(inValue);
            return retVal.Body.HelloResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HelloWebClient.HelloWebServiceNamespace.HelloResponse> HelloWebClient.HelloWebServiceNamespace.HelloWebServiceSoap.HelloAsync(HelloWebClient.HelloWebServiceNamespace.HelloRequest request) {
            return base.Channel.HelloAsync(request);
        }
        
        public System.Threading.Tasks.Task<HelloWebClient.HelloWebServiceNamespace.HelloResponse> HelloAsync(string who) {
            HelloWebClient.HelloWebServiceNamespace.HelloRequest inValue = new HelloWebClient.HelloWebServiceNamespace.HelloRequest();
            inValue.Body = new HelloWebClient.HelloWebServiceNamespace.HelloRequestBody();
            inValue.Body.who = who;
            return ((HelloWebClient.HelloWebServiceNamespace.HelloWebServiceSoap)(this)).HelloAsync(inValue);
        }
    }
}
