//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace L01E02.WinFormPersonServiceClient.PersonServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PersonServiceReference.IPersonService")]
    public interface IPersonService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonService/EditFirstname", ReplyAction="http://tempuri.org/IPersonService/EditFirstnameResponse")]
        bool EditFirstname(string newFirstname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonService/EditFirstname", ReplyAction="http://tempuri.org/IPersonService/EditFirstnameResponse")]
        System.Threading.Tasks.Task<bool> EditFirstnameAsync(string newFirstname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonService/EditLastname", ReplyAction="http://tempuri.org/IPersonService/EditLastnameResponse")]
        bool EditLastname(string newLastname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonService/EditLastname", ReplyAction="http://tempuri.org/IPersonService/EditLastnameResponse")]
        System.Threading.Tasks.Task<bool> EditLastnameAsync(string newLastname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonService/EditAddress", ReplyAction="http://tempuri.org/IPersonService/EditAddressResponse")]
        bool EditAddress(string newAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonService/EditAddress", ReplyAction="http://tempuri.org/IPersonService/EditAddressResponse")]
        System.Threading.Tasks.Task<bool> EditAddressAsync(string newAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonService/EditPhone", ReplyAction="http://tempuri.org/IPersonService/EditPhoneResponse")]
        bool EditPhone(int newPhone);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonService/EditPhone", ReplyAction="http://tempuri.org/IPersonService/EditPhoneResponse")]
        System.Threading.Tasks.Task<bool> EditPhoneAsync(int newPhone);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonService/GetFullname", ReplyAction="http://tempuri.org/IPersonService/GetFullnameResponse")]
        string GetFullname();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonService/GetFullname", ReplyAction="http://tempuri.org/IPersonService/GetFullnameResponse")]
        System.Threading.Tasks.Task<string> GetFullnameAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonService/GetAddress", ReplyAction="http://tempuri.org/IPersonService/GetAddressResponse")]
        string GetAddress();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonService/GetAddress", ReplyAction="http://tempuri.org/IPersonService/GetAddressResponse")]
        System.Threading.Tasks.Task<string> GetAddressAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPersonServiceChannel : L01E02.WinFormPersonServiceClient.PersonServiceReference.IPersonService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PersonServiceClient : System.ServiceModel.ClientBase<L01E02.WinFormPersonServiceClient.PersonServiceReference.IPersonService>, L01E02.WinFormPersonServiceClient.PersonServiceReference.IPersonService {
        
        public PersonServiceClient() {
        }
        
        public PersonServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PersonServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PersonServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PersonServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool EditFirstname(string newFirstname) {
            return base.Channel.EditFirstname(newFirstname);
        }
        
        public System.Threading.Tasks.Task<bool> EditFirstnameAsync(string newFirstname) {
            return base.Channel.EditFirstnameAsync(newFirstname);
        }
        
        public bool EditLastname(string newLastname) {
            return base.Channel.EditLastname(newLastname);
        }
        
        public System.Threading.Tasks.Task<bool> EditLastnameAsync(string newLastname) {
            return base.Channel.EditLastnameAsync(newLastname);
        }
        
        public bool EditAddress(string newAddress) {
            return base.Channel.EditAddress(newAddress);
        }
        
        public System.Threading.Tasks.Task<bool> EditAddressAsync(string newAddress) {
            return base.Channel.EditAddressAsync(newAddress);
        }
        
        public bool EditPhone(int newPhone) {
            return base.Channel.EditPhone(newPhone);
        }
        
        public System.Threading.Tasks.Task<bool> EditPhoneAsync(int newPhone) {
            return base.Channel.EditPhoneAsync(newPhone);
        }
        
        public string GetFullname() {
            return base.Channel.GetFullname();
        }
        
        public System.Threading.Tasks.Task<string> GetFullnameAsync() {
            return base.Channel.GetFullnameAsync();
        }
        
        public string GetAddress() {
            return base.Channel.GetAddress();
        }
        
        public System.Threading.Tasks.Task<string> GetAddressAsync() {
            return base.Channel.GetAddressAsync();
        }
    }
}
